In [1]:

import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2 , np.nan,4],
    "B": [ 5.1, np.nan,6.6,8.8],
    "C": ["foo","zoo","bar", np.nan],
    'D':[6,7,8,9]
})
print(df)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  NaN  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  NaN  9

In [4]:
df.dropna(axis=1)

   D
0  6
1  7
2  8
3  9

In [6]:
df.fillna(1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  1.0  zoo  7
2  1.0  6.6  bar  8
3  4.0  8.8    1  9

In [7]:
df

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  NaN  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  NaN  9

In [11]:
df.ffill(axis=1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  2.0  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  8.8  9

In [13]:
df.bfill(axis=1)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  zoo  zoo  7
2  6.6  6.6  bar  8
3  4.0  8.8    9  9