In [1]:
import pandas as pd
df=pd.read_csv('sp500_companies.csv')
df

,Company name,Symbol,Sector[15],Date added[16]
0,Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
1,Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
2,Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
4,Axis Bank,AXISBANK,Financial Services,27 March 2009
5,Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
6,Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat Electronics,BEL,Capital Goods,30 September 2024
9,Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Cipla,CIPLA,Healthcare,7 October 1998
11,Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
12,Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
13,Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
14,Eternal,ETERNAL,Consumer Services,28 March 2025
15,Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
16,HCLTech,HCLTECH,Information Technology,28 October 2002
17,HDFC Bank,HDFCBANK,Financial Services,22 April 1996
18,HDFC Life,HDFCLIFE,Financial Services,31 July 2020
19,Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
20,Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
21,ICICI Bank,ICICIBANK,Financial Services,25 January 2002
22,IndiGo,INDIGO,Services,30 September 2025
23,Infosys,INFY,Information Technology,7 October 1998
24,ITC,ITC,Fast Moving Consumer Goods,22 April 1996
25,Jio Financial Services,JIOFIN,Financial Services,28 March 2025
26,JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
27,Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
28,Larsen & Toubro,LT,Construction,10 December 2004[e]
29,Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
30,Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
31,Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
32,Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
33,NTPC,NTPC,Power,24 September 2007
34,Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
35,Power Grid,POWERGRID,Power,14 March 2008
36,Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
37,SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
38,Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
39,State Bank of India,SBIN,Financial Services,22 April 1996
40,Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
41,Tata Consultancy Services,TCS,Information Technology,25 February 2005
42,Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
43,Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
44,Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
45,Tech Mahindra,TECHM,Information Technology,28 March 2014
46,Titan Company,TITAN,Consumer Durables,2 April 2018
47,Trent,TRENT,Consumer Services,30 September 2024
48,UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013[h]

In [2]:
"HELLO".lower()

'hello'

In [5]:
df['Symbol'].str.lower()

0       adanient
1     adaniports
2     apollohosp
3     asianpaint
4       axisbank
5     bajaj-auto
6     bajfinance
7     bajajfinsv
8            bel
9     bhartiartl
10         cipla
11     coalindia
12       drreddy
13     eichermot
14       eternal
15        grasim
16       hcltech
17      hdfcbank
18      hdfclife
19      hindalco
20    hindunilvr
21     icicibank
22        indigo
23          infy
24           itc
25        jiofin
26      jswsteel
27     kotakbank
28            lt
29           m&m
30        maruti
31     maxhealth
32     nestleind
33          ntpc
34          ongc
35     powergrid
36      reliance
37       sbilife
38    shriramfin
39          sbin
40     sunpharma
41           tcs
42    tataconsum
43          tmpv
44     tatasteel
45         techm
46         titan
47         trent
48    ultracemco
49         wipro
Name: Symbol, dtype: str

In [8]:
l1=[]
for i in df['Company name']:
    l1.append(i.replace(' ','-'))
l1

['Adani-Enterprises',
 'Adani-Ports-&-SEZ',
 'Apollo-Hospitals',
 'Asian-Paints',
 'Axis-Bank',
 'Bajaj-Auto',
 'Bajaj-Finance',
 'Bajaj-Finserv',
 'Bharat-Electronics',
 'Bharti-Airtel',
 'Cipla',
 'Coal-India',
 "Dr.-Reddy's-Laboratories",
 'Eicher-Motors',
 'Eternal',
 'Grasim-Industries',
 'HCLTech',
 'HDFC-Bank',
 'HDFC-Life',
 'Hindalco-Industries',
 'Hindustan-Unilever',
 'ICICI-Bank',
 'IndiGo',
 'Infosys',
 'ITC',
 'Jio-Financial-Services',
 'JSW-Steel',
 'Kotak-Mahindra-Bank',
 'Larsen-&-Toubro',
 'Mahindra-&-Mahindra',
 'Maruti-Suzuki',
 'Max-Healthcare',
 'Nestlé-India',
 'NTPC',
 'Oil-and-Natural-Gas-Corporation',
 'Power-Grid',
 'Reliance-Industries',
 'SBI-Life-Insurance-Company',
 'Shriram-Finance',
 'State-Bank-of-India',
 'Sun-Pharma',
 'Tata-Consultancy-Services',
 'Tata-Consumer-Products',
 'Tata-Motors-Passenger-Vehicles',
 'Tata-Steel',
 'Tech-Mahindra',
 'Titan-Company',
 'Trent',
 'UltraTech-Cement',
 'Wipro']

In [9]:
df['Company name']=l1
df

,Company name,Symbol,Sector[15],Date added[16]
0,Adani-Enterprises,ADANIENT,Metals & Mining,30 September 2022
1,Adani-Ports-&-SEZ,ADANIPORTS,Services,28 September 2015
2,Apollo-Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian-Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
4,Axis-Bank,AXISBANK,Financial Services,27 March 2009
5,Bajaj-Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
6,Bajaj-Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj-Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat-Electronics,BEL,Capital Goods,30 September 2024
9,Bharti-Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Cipla,CIPLA,Healthcare,7 October 1998
11,Coal-India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
12,Dr.-Reddy's-Laboratories,DRREDDY,Healthcare,1 October 2010[c]
13,Eicher-Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
14,Eternal,ETERNAL,Consumer Services,28 March 2025
15,Grasim-Industries,GRASIM,Construction Materials,2 April 2018[d]
16,HCLTech,HCLTECH,Information Technology,28 October 2002
17,HDFC-Bank,HDFCBANK,Financial Services,22 April 1996
18,HDFC-Life,HDFCLIFE,Financial Services,31 July 2020
19,Hindalco-Industries,HINDALCO,Metals & Mining,22 April 1996
20,Hindustan-Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
21,ICICI-Bank,ICICIBANK,Financial Services,25 January 2002
22,IndiGo,INDIGO,Services,30 September 2025
23,Infosys,INFY,Information Technology,7 October 1998
24,ITC,ITC,Fast Moving Consumer Goods,22 April 1996
25,Jio-Financial-Services,JIOFIN,Financial Services,28 March 2025
26,JSW-Steel,JSWSTEEL,Metals & Mining,28 September 2018
27,Kotak-Mahindra-Bank,KOTAKBANK,Financial Services,8 April 2010
28,Larsen-&-Toubro,LT,Construction,10 December 2004[e]
29,Mahindra-&-Mahindra,M&M,Automobile and Auto Components,18 September 1996
30,Maruti-Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
31,Max-Healthcare,MAXHEALTH,Healthcare,30 September 2025
32,Nestlé-India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
33,NTPC,NTPC,Power,24 September 2007
34,Oil-and-Natural-Gas-Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
35,Power-Grid,POWERGRID,Power,14 March 2008
36,Reliance-Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
37,SBI-Life-Insurance-Company,SBILIFE,Financial Services,25 September 2020
38,Shriram-Finance,SHRIRAMFIN,Financial Services,28 March 2024
39,State-Bank-of-India,SBIN,Financial Services,22 April 1996
40,Sun-Pharma,SUNPHARMA,Healthcare,17 January 2002
41,Tata-Consultancy-Services,TCS,Information Technology,25 February 2005
42,Tata-Consumer-Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
43,Tata-Motors-Passenger-Vehicles,TMPV,Automobile and Auto Components,22 April 1996
44,Tata-Steel,TATASTEEL,Metals & Mining,22 April 1996
45,Tech-Mahindra,TECHM,Information Technology,28 March 2014
46,Titan-Company,TITAN,Consumer Durables,2 April 2018
47,Trent,TRENT,Consumer Services,30 September 2024
48,UltraTech-Cement,ULTRACEMCO,Construction Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013[h]

In [11]:
df['Date added[16]']=df['Date added[16]'].str.replace(' ','-')
df

,Company name,Symbol,Sector[15],Date added[16]
0,Adani-Enterprises,ADANIENT,Metals & Mining,30-September-2022
1,Adani-Ports-&-SEZ,ADANIPORTS,Services,28-September-2015
2,Apollo-Hospitals,APOLLOHOSP,Healthcare,31-March-2022
3,Asian-Paints,ASIANPAINT,Consumer Durables,27-April-2012[a]
4,Axis-Bank,AXISBANK,Financial Services,27-March-2009
5,Bajaj-Auto,BAJAJ-AUTO,Automobile and Auto Components,1-October-2010[b]
6,Bajaj-Finance,BAJFINANCE,Financial Services,29-September-2017
7,Bajaj-Finserv,BAJAJFINSV,Financial Services,2-April-2018
8,Bharat-Electronics,BEL,Capital Goods,30-September-2024
9,Bharti-Airtel,BHARTIARTL,Telecommunication,1-March-2004
10,Cipla,CIPLA,Healthcare,7-October-1998
11,Coal-India,COALINDIA,"Oil, Gas & Consumable Fuels",10-October-2011
12,Dr.-Reddy's-Laboratories,DRREDDY,Healthcare,1-October-2010[c]
13,Eicher-Motors,EICHERMOT,Automobile and Auto Components,1-April-2016
14,Eternal,ETERNAL,Consumer Services,28-March-2025
15,Grasim-Industries,GRASIM,Construction Materials,2-April-2018[d]
16,HCLTech,HCLTECH,Information Technology,28-October-2002
17,HDFC-Bank,HDFCBANK,Financial Services,22-April-1996
18,HDFC-Life,HDFCLIFE,Financial Services,31-July-2020
19,Hindalco-Industries,HINDALCO,Metals & Mining,22-April-1996
20,Hindustan-Unilever,HINDUNILVR,Fast Moving Consumer Goods,22-April-1996
21,ICICI-Bank,ICICIBANK,Financial Services,25-January-2002
22,IndiGo,INDIGO,Services,30-September-2025
23,Infosys,INFY,Information Technology,7-October-1998
24,ITC,ITC,Fast Moving Consumer Goods,22-April-1996
25,Jio-Financial-Services,JIOFIN,Financial Services,28-March-2025
26,JSW-Steel,JSWSTEEL,Metals & Mining,28-September-2018
27,Kotak-Mahindra-Bank,KOTAKBANK,Financial Services,8-April-2010
28,Larsen-&-Toubro,LT,Construction,10-December-2004[e]
29,Mahindra-&-Mahindra,M&M,Automobile and Auto Components,18-September-1996
30,Maruti-Suzuki,MARUTI,Automobile and Auto Components,1-March-2004
31,Max-Healthcare,MAXHEALTH,Healthcare,30-September-2025
32,Nestlé-India,NESTLEIND,Fast Moving Consumer Goods,27-September-2019[f]
33,NTPC,NTPC,Power,24-September-2007
34,Oil-and-Natural-Gas-Corporation,ONGC,"Oil, Gas & Consumable Fuels",12-April-2004
35,Power-Grid,POWERGRID,Power,14-March-2008
36,Reliance-Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22-April-1996
37,SBI-Life-Insurance-Company,SBILIFE,Financial Services,25-September-2020
38,Shriram-Finance,SHRIRAMFIN,Financial Services,28-March-2024
39,State-Bank-of-India,SBIN,Financial Services,22-April-1996
40,Sun-Pharma,SUNPHARMA,Healthcare,17-January-2002
41,Tata-Consultancy-Services,TCS,Information Technology,25-February-2005
42,Tata-Consumer-Products,TATACONSUM,Fast Moving Consumer Goods,31-March-2021[g]
43,Tata-Motors-Passenger-Vehicles,TMPV,Automobile and Auto Components,22-April-1996
44,Tata-Steel,TATASTEEL,Metals & Mining,22-April-1996
45,Tech-Mahindra,TECHM,Information Technology,28-March-2014
46,Titan-Company,TITAN,Consumer Durables,2-April-2018
47,Trent,TRENT,Consumer Services,30-September-2024
48,UltraTech-Cement,ULTRACEMCO,Construction Materials,28-September-2012
49,Wipro,WIPRO,Information Technology,27-September-2013[h]

In [13]:
l1=[]
for i in df['Date added[16]']:
    if i[-3]=='[':
        l1.append(i[:-3])
    else:
        l1.append(i)
l1
df['Date added[16]']=l1

In [14]:
df

,Company name,Symbol,Sector[15],Date added[16]
0,Adani-Enterprises,ADANIENT,Metals & Mining,30-September-2022
1,Adani-Ports-&-SEZ,ADANIPORTS,Services,28-September-2015
2,Apollo-Hospitals,APOLLOHOSP,Healthcare,31-March-2022
3,Asian-Paints,ASIANPAINT,Consumer Durables,27-April-2012
4,Axis-Bank,AXISBANK,Financial Services,27-March-2009
5,Bajaj-Auto,BAJAJ-AUTO,Automobile and Auto Components,1-October-2010
6,Bajaj-Finance,BAJFINANCE,Financial Services,29-September-2017
7,Bajaj-Finserv,BAJAJFINSV,Financial Services,2-April-2018
8,Bharat-Electronics,BEL,Capital Goods,30-September-2024
9,Bharti-Airtel,BHARTIARTL,Telecommunication,1-March-2004
10,Cipla,CIPLA,Healthcare,7-October-1998
11,Coal-India,COALINDIA,"Oil, Gas & Consumable Fuels",10-October-2011
12,Dr.-Reddy's-Laboratories,DRREDDY,Healthcare,1-October-2010
13,Eicher-Motors,EICHERMOT,Automobile and Auto Components,1-April-2016
14,Eternal,ETERNAL,Consumer Services,28-March-2025
15,Grasim-Industries,GRASIM,Construction Materials,2-April-2018
16,HCLTech,HCLTECH,Information Technology,28-October-2002
17,HDFC-Bank,HDFCBANK,Financial Services,22-April-1996
18,HDFC-Life,HDFCLIFE,Financial Services,31-July-2020
19,Hindalco-Industries,HINDALCO,Metals & Mining,22-April-1996
20,Hindustan-Unilever,HINDUNILVR,Fast Moving Consumer Goods,22-April-1996
21,ICICI-Bank,ICICIBANK,Financial Services,25-January-2002
22,IndiGo,INDIGO,Services,30-September-2025
23,Infosys,INFY,Information Technology,7-October-1998
24,ITC,ITC,Fast Moving Consumer Goods,22-April-1996
25,Jio-Financial-Services,JIOFIN,Financial Services,28-March-2025
26,JSW-Steel,JSWSTEEL,Metals & Mining,28-September-2018
27,Kotak-Mahindra-Bank,KOTAKBANK,Financial Services,8-April-2010
28,Larsen-&-Toubro,LT,Construction,10-December-2004
29,Mahindra-&-Mahindra,M&M,Automobile and Auto Components,18-September-1996
30,Maruti-Suzuki,MARUTI,Automobile and Auto Components,1-March-2004
31,Max-Healthcare,MAXHEALTH,Healthcare,30-September-2025
32,Nestlé-India,NESTLEIND,Fast Moving Consumer Goods,27-September-2019
33,NTPC,NTPC,Power,24-September-2007
34,Oil-and-Natural-Gas-Corporation,ONGC,"Oil, Gas & Consumable Fuels",12-April-2004
35,Power-Grid,POWERGRID,Power,14-March-2008
36,Reliance-Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22-April-1996
37,SBI-Life-Insurance-Company,SBILIFE,Financial Services,25-September-2020
38,Shriram-Finance,SHRIRAMFIN,Financial Services,28-March-2024
39,State-Bank-of-India,SBIN,Financial Services,22-April-1996
40,Sun-Pharma,SUNPHARMA,Healthcare,17-January-2002
41,Tata-Consultancy-Services,TCS,Information Technology,25-February-2005
42,Tata-Consumer-Products,TATACONSUM,Fast Moving Consumer Goods,31-March-2021
43,Tata-Motors-Passenger-Vehicles,TMPV,Automobile and Auto Components,22-April-1996
44,Tata-Steel,TATASTEEL,Metals & Mining,22-April-1996
45,Tech-Mahindra,TECHM,Information Technology,28-March-2014
46,Titan-Company,TITAN,Consumer Durables,2-April-2018
47,Trent,TRENT,Consumer Services,30-September-2024
48,UltraTech-Cement,ULTRACEMCO,Construction Materials,28-September-2012
49,Wipro,WIPRO,Information Technology,27-September-2013

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company name    50 non-null     str
 1   Symbol          50 non-null     str
 2   Sector[15]      50 non-null     str
 3   Date added[16]  50 non-null     str
dtypes: str(4)
memory usage: 1.7 KB

#how to chage datatype of a column

In [22]:
df2=pd.read_csv('sp500.csv')
df2=df2.astype({'Price':'int'})
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    102 non-null    str
 1   Sector  102 non-null    str
 2   Price   102 non-null    int64
 3   EPS     101 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 3.3 KB

In [23]:
df2

                           Name                  Sector  Price    EPS
0                     Apple Inc  Information Technology    170   9.20
1                    Abbvie Inc             Health Care     93   5.31
2           Abbott Laboratories             Health Care     55   2.41
3                 Accenture Plc  Information Technology    145    NaN
4                  Allergan Plc             Health Care    171  15.42
..                          ...                     ...    ...    ...
97   Verizon Communications Inc      Telecommunications     45   3.75
98     Walgreens Boots Alliance        Consumer Staples     70   5.10
99        Wells Fargo & Company              Financials     54   4.14
100             Wal-Mart Stores        Consumer Staples     96   4.36
101            Exxon Mobil Corp                  Energy     80   3.56

[102 rows x 4 columns]

In [26]:
from io import StringIO
import ssl
import urllib.request
import certifi

url = 'https://www.screener.in/screens/281185/nifty-50/'
ssl_context = ssl.create_default_context(cafile=certifi.where())

with urllib.request.urlopen(url, context=ssl_context) as response:
    html = response.read().decode('utf-8')

df9 = pd.read_html(StringIO(html))
df=df9[0]
df

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1414.40,24.94,1914032.40,0.39,22290.00,0.57,264905.00,10.38,9.69
1,2.,HDFC Bank,780.45,16.12,1201267.28,1.41,20691.04,12.18,87066.94,2.38,7.51
2,3.,Bharti Airtel,1846.10,34.36,1052665.66,0.87,8502.80,-18.76,53981.60,19.62,13.48
3,4.,SBI,1058.00,12.05,976599.34,1.50,22175.72,13.07,130589.72,4.76,6.47
4,5.,ICICI Bank,1245.40,16.84,891569.27,0.88,13481.13,-2.68,48363.84,2.82,7.87
5,6.,TCS,2390.60,16.92,864940.00,2.51,10720.00,6.69,67087.00,4.87,64.63
6,7.,Bajaj Finance,830.55,28.38,516808.23,0.53,4066.01,-2.16,21213.89,17.63,11.35
7,8.,Infosys,1255.90,17.65,509316.57,3.42,6666.00,10.79,45479.00,8.90,37.50
8,9.,Life Insurance,776.75,9.27,491294.20,1.54,12907.90,17.46,235954.23,15.81,53.13
9,10.,Hind. Unilever,2082.70,44.83,489349.37,2.06,6603.00,9.62,16441.00,5.69,27.85
10,11.,Larsen & Toubro,3434.80,27.69,472495.05,0.99,3824.65,29.35,71449.70,10.49,14.49
11,12.,Sun Pharma.Inds.,1777.10,35.13,426385.82,0.90,3381.17,18.73,15520.54,13.49,20.21
12,13.,Maruti Suzuki,12601.00,26.53,396178.68,1.07,3879.10,4.08,49904.10,28.74,21.70
13,14.,M & M,3066.10,23.87,381278.37,0.83,5021.47,54.61,52099.75,25.63,13.93
14,15.,ITC,299.95,18.22,375821.40,4.78,5018.45,9.62,20047.30,6.69,36.79
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Axis Bank,1203.90,14.25,374138.52,0.08,7059.78,3.98,33709.17,4.81,7.11
17,17.,NTPC,380.95,15.28,369394.50,2.19,5597.05,8.42,45845.68,1.72,9.95
18,18.,Kotak Mah. Bank,366.75,19.41,364786.31,0.14,4924.29,4.75,17506.80,5.25,8.17
19,19.,Titan Company,4106.60,74.71,364578.26,0.27,1684.00,71.73,25416.00,43.27,19.14
20,20.,HCL Technologies,1333.70,21.08,361921.51,4.05,4082.00,4.19,33872.00,13.32,31.61
21,21.,O N G C,265.40,8.79,333880.61,4.62,11946.42,16.36,167422.93,0.13,12.04
22,22.,UltraTech Cem.,10934.00,41.48,322202.21,0.71,1729.44,31.88,21829.68,22.78,10.89
23,23.,Adani Ports,1365.40,24.90,314582.58,0.51,3042.93,24.90,9704.59,21.86,13.80
24,24.,Bharat Electron,426.10,52.23,311469.68,0.56,1579.70,20.45,7153.85,23.97,38.88
25,25.,Adani Power,151.54,25.51,292240.26,0.00,2488.09,-18.89,12451.44,-8.92,22.54

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              26 non-null     str
 1   Name               26 non-null     str
 2   CMP  Rs.           26 non-null     str
 3   P/E                26 non-null     str
 4   Mar Cap  Rs.Cr.    26 non-null     str
 5   Div Yld  %         26 non-null     str
 6   NP Qtr  Rs.Cr.     26 non-null     str
 7   Qtr Profit Var  %  26 non-null     str
 8   Sales Qtr  Rs.Cr.  26 non-null     str
 9   Qtr Sales Var  %   26 non-null     str
 10  ROCE  %            26 non-null     str
dtypes: str(11)
memory usage: 2.4 KB

In [28]:
df=df.drop(15,axis=0)
df

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1414.40,24.94,1914032.40,0.39,22290.00,0.57,264905.00,10.38,9.69
1,2.,HDFC Bank,780.45,16.12,1201267.28,1.41,20691.04,12.18,87066.94,2.38,7.51
2,3.,Bharti Airtel,1846.10,34.36,1052665.66,0.87,8502.80,-18.76,53981.60,19.62,13.48
3,4.,SBI,1058.00,12.05,976599.34,1.50,22175.72,13.07,130589.72,4.76,6.47
4,5.,ICICI Bank,1245.40,16.84,891569.27,0.88,13481.13,-2.68,48363.84,2.82,7.87
5,6.,TCS,2390.60,16.92,864940.00,2.51,10720.00,6.69,67087.00,4.87,64.63
6,7.,Bajaj Finance,830.55,28.38,516808.23,0.53,4066.01,-2.16,21213.89,17.63,11.35
7,8.,Infosys,1255.90,17.65,509316.57,3.42,6666.00,10.79,45479.00,8.90,37.50
8,9.,Life Insurance,776.75,9.27,491294.20,1.54,12907.90,17.46,235954.23,15.81,53.13
9,10.,Hind. Unilever,2082.70,44.83,489349.37,2.06,6603.00,9.62,16441.00,5.69,27.85
10,11.,Larsen & Toubro,3434.80,27.69,472495.05,0.99,3824.65,29.35,71449.70,10.49,14.49
11,12.,Sun Pharma.Inds.,1777.10,35.13,426385.82,0.90,3381.17,18.73,15520.54,13.49,20.21
12,13.,Maruti Suzuki,12601.00,26.53,396178.68,1.07,3879.10,4.08,49904.10,28.74,21.70
13,14.,M & M,3066.10,23.87,381278.37,0.83,5021.47,54.61,52099.75,25.63,13.93
14,15.,ITC,299.95,18.22,375821.40,4.78,5018.45,9.62,20047.30,6.69,36.79
16,16.,Axis Bank,1203.90,14.25,374138.52,0.08,7059.78,3.98,33709.17,4.81,7.11
17,17.,NTPC,380.95,15.28,369394.50,2.19,5597.05,8.42,45845.68,1.72,9.95
18,18.,Kotak Mah. Bank,366.75,19.41,364786.31,0.14,4924.29,4.75,17506.80,5.25,8.17
19,19.,Titan Company,4106.60,74.71,364578.26,0.27,1684.00,71.73,25416.00,43.27,19.14
20,20.,HCL Technologies,1333.70,21.08,361921.51,4.05,4082.00,4.19,33872.00,13.32,31.61
21,21.,O N G C,265.40,8.79,333880.61,4.62,11946.42,16.36,167422.93,0.13,12.04
22,22.,UltraTech Cem.,10934.00,41.48,322202.21,0.71,1729.44,31.88,21829.68,22.78,10.89
23,23.,Adani Ports,1365.40,24.90,314582.58,0.51,3042.93,24.90,9704.59,21.86,13.80
24,24.,Bharat Electron,426.10,52.23,311469.68,0.56,1579.70,20.45,7153.85,23.97,38.88
25,25.,Adani Power,151.54,25.51,292240.26,0.00,2488.09,-18.89,12451.44,-8.92,22.54

In [29]:
df['P/E']=df['P/E'].astype('float')
df.info()

<class 'pandas.DataFrame'>
Index: 25 entries, 0 to 25
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              25 non-null     str
 1   Name               25 non-null     str
 2   CMP  Rs.           25 non-null     str
 3   P/E                25 non-null     float64
 4   Mar Cap  Rs.Cr.    25 non-null     str
 5   Div Yld  %         25 non-null     str
 6   NP Qtr  Rs.Cr.     25 non-null     str
 7   Qtr Profit Var  %  25 non-null     str
 8   Sales Qtr  Rs.Cr.  25 non-null     str
 9   Qtr Sales Var  %   25 non-null     str
 10  ROCE  %            25 non-null     str
dtypes: float64(1), str(10)
memory usage: 2.3 KB

In [33]:
df[df['P/E']>40]['Name'].to_list()

['Hind. Unilever', 'Titan Company', 'UltraTech Cem.', 'Bharat Electron']