In [1]:
!pip3 install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/algo trading 2026/batch36/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.1

In [1]:
import pandas as pd
a=[[1,2,3],[4,5,6],[7,8,9]]
df1=pd.DataFrame(a,index=['row1','row2','row3'],columns=['col1','col2','col3'])
df1

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9

In [5]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
np1=np.array(a)
print(np1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [8]:
df2=pd.DataFrame(np1,index=['r1','r2','r3'],columns=['c1','c2','c3'])
df2

    c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [9]:
d1={'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['New York','Los Angeles','Chicago']}
df3=pd.DataFrame(d1)
df3

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [10]:
l1=[{'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'Los Angeles'},
    {'Name':'Charlie','Age':35,'City':'Chicago'}]
df4=pd.DataFrame(l1)
df4

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [6]:
df=pd.read_csv(r'/Users/algo trading 2026/batch36/11_pandas/sp500.csv')
df

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [2]:
df7=pd.read_excel(r'/Users/algo trading 2026/batch36/11_pandas/e500.xlsx')
df7

,Unnamed: 0,Name,Sector,Price,EPS
0,0,Apple Inc,Information Technology,170.12,9.20
1,1,Abbvie Inc,Health Care,93.29,5.31
2,2,Abbott Laboratories,Health Care,55.28,2.41
3,3,Accenture Plc,Information Technology,145.30,NaN
4,4,Allergan Plc,Health Care,171.81,15.42
...,...,...,...,...,...
97,97,Verizon Communications Inc,Telecommunications,45.85,3.75
98,98,Walgreens Boots Alliance,Consumer Staples,70.25,5.10
99,99,Wells Fargo & Company,Financials,54.02,4.14
100,100,Wal-Mart Stores,Consumer Staples,96.08,4.36
101,101,Exxon Mobil Corp,Energy,80.31,3.56

In [4]:
!pip3 install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [4]:
from io import StringIO
import ssl
import urllib.request
import certifi

url = 'https://www.screener.in/screens/281185/nifty-50/'
ssl_context = ssl.create_default_context(cafile=certifi.where())

with urllib.request.urlopen(url, context=ssl_context) as response:
    html = response.read().decode('utf-8')

df9 = pd.read_html(StringIO(html))
df9[0]

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1380.70,24.35,1868897.82,0.40,22290.00,0.57,264905.00,10.38,9.69
1,2.,HDFC Bank,817.00,16.88,1257769.36,1.35,20691.04,12.18,87066.94,2.38,7.51
2,3.,Bharti Airtel,1803.40,33.57,1028603.19,0.89,8502.80,-18.76,53981.60,19.62,13.48
3,4.,SBI,1047.00,11.92,966312.09,1.52,22175.72,13.07,130589.72,4.76,6.47
4,5.,ICICI Bank,1254.80,16.97,898486.45,0.88,13481.13,-2.68,48363.84,2.82,7.87
5,6.,TCS,2410.50,17.06,871979.34,2.49,10720.00,6.69,67087.00,4.87,64.63
6,7.,Bajaj Finance,855.05,29.20,531776.06,0.51,4066.01,-2.16,21213.89,17.63,11.35
7,8.,Hind. Unilever,2160.00,46.53,507856.32,1.99,6603.00,9.62,16441.00,5.69,27.85
8,9.,Infosys,1248.30,17.54,506214.48,3.44,6666.00,10.79,45479.00,8.90,37.50
9,10.,Life Insurance,772.70,9.22,488824.61,1.55,12907.90,17.46,235954.23,15.81,53.13
10,11.,Larsen & Toubro,3439.00,27.72,472888.46,0.99,3824.65,29.35,71449.70,10.49,14.49
11,12.,Sun Pharma.Inds.,1801.60,35.62,432335.24,0.89,3381.17,18.73,15520.54,13.49,20.21
12,13.,Maruti Suzuki,12591.00,26.50,395709.17,1.07,3879.10,4.08,49904.10,28.74,21.70
13,14.,ITC,301.45,18.32,377942.19,4.76,5018.45,9.62,20047.30,6.69,36.79
14,15.,NTPC,384.45,15.42,372740.61,2.17,5597.05,8.42,45845.68,1.72,9.95
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Axis Bank,1197.30,14.18,372274.36,0.08,7059.78,3.98,33709.17,4.81,7.11
17,17.,Kotak Mah. Bank,366.85,19.41,364885.77,0.14,4924.29,4.75,17506.80,5.25,8.17
18,18.,M & M,2931.10,22.80,364298.44,0.86,5021.47,54.61,52099.75,25.63,13.93
19,19.,Titan Company,4073.20,74.15,361845.26,0.27,1684.00,71.73,25416.00,43.27,19.14
20,20.,HCL Technologies,1325.40,20.94,359576.51,4.07,4082.00,4.19,33872.00,13.32,31.61
21,21.,O N G C,264.10,8.75,332368.02,4.64,11946.42,16.36,167422.93,0.13,12.04
22,22.,Bharat Electron,439.40,53.83,321050.11,0.55,1579.70,20.45,7153.85,23.97,38.88
23,23.,Adani Ports,1363.20,24.86,314120.85,0.51,3042.93,24.90,9704.59,21.86,13.80
24,24.,UltraTech Cem.,10616.00,40.27,312787.68,0.73,1729.44,31.88,21829.68,22.78,10.89
25,25.,Coal India,467.00,9.64,287768.81,5.67,7165.98,-15.85,34924.19,-5.25,48.04

In [7]:
!pip3 install lxml

Collecting lxml
  Using cached lxml-6.0.2-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.6 kB)
Using cached lxml-6.0.2-cp313-cp313-macosx_10_13_universal2.whl (8.6 MB)
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [9]:
!pip3 install certifi

Collecting certifi
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: certifi
Successfully installed certifi-2026.2.25

In [8]:
df.index

RangeIndex(start=0, stop=102, step=1)

In [10]:
list(df.columns)

['Name', 'Sector', 'Price', 'EPS']

In [11]:
df.shape

(102, 4)

In [13]:
df.head(10)

                           Name                  Sector    Price    EPS
0                     Apple Inc  Information Technology   170.12   9.20
1                    Abbvie Inc             Health Care    93.29   5.31
2           Abbott Laboratories             Health Care    55.28   2.41
3                 Accenture Plc  Information Technology   145.30    NaN
4                  Allergan Plc             Health Care   171.81  15.42
5  American International Group              Financials    59.50   2.51
6                 Allstate Corp              Financials   100.50   6.79
7                         Amgen             Health Care   168.93  12.58
8               Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
9      American Express Company              Financials    93.92   5.22

In [14]:
df.tail(10)

                           Name                  Sector   Price   EPS
92           Union Pacific Corp             Industrials  115.58  5.66
93        United Parcel Service             Industrials  113.20  5.98
94                 U.S. Bancorp              Financials   51.88  3.37
95     United Technologies Corp             Industrials  117.05  6.62
96                     Visa Inc  Information Technology  110.27  3.48
97   Verizon Communications Inc      Telecommunications   45.85  3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25  5.10
99        Wells Fargo & Company              Financials   54.02  4.14
100             Wal-Mart Stores        Consumer Staples   96.08  4.36
101            Exxon Mobil Corp                  Energy   80.31  3.56

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    102 non-null    str
 1   Sector  102 non-null    str
 2   Price   102 non-null    float64
 3   EPS     101 non-null    float64
dtypes: float64(2), str(2)
memory usage: 3.3 KB

In [16]:
df.describe()

             Price        EPS
count   102.000000  101.00000
mean    150.500686    6.49099
std     240.768463    8.62033
min      12.110000    0.02000
25%      54.335000    2.87000
50%      88.295000    4.36000
75%     151.032500    6.62000
max    1762.230000   74.45000

In [ ]:
#series->single column of data
df['Price']

0      170.12
1       93.29
2       55.28
3      145.30
4      171.81
        ...
97      45.85
98      70.25
99      54.02
100     96.08
101     80.31
Name: Price, Length: 102, dtype: float64

In [20]:
df.EPS

0       9.20
1       5.31
2       2.41
3        NaN
4      15.42
       ...
97      3.75
98      5.10
99      4.14
100     4.36
101     3.56
Name: EPS, Length: 102, dtype: float64

In [22]:
df['new']=df['Price']+df['EPS']

In [26]:
df['new']=df['Price']*2

In [32]:
df[df['Price']>200]

                      Name                  Sector    Price    EPS      new
8          Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94  2253.64
10          Boeing Company             Industrials   265.04   9.75   530.08
12              Biogen Inc             Health Care   311.92  21.59   623.84
14               Blackrock              Financials   474.05  21.55   948.10
20    Charter Communicatio  Consumer Discretionary   346.20   1.61   692.40
37              Fedex Corp             Industrials   217.75  11.91   435.50
44        Alphabet Class C  Information Technology  1018.48  29.87  2036.96
45        Alphabet Class A  Information Technology  1034.09  29.87  2068.18
46     Goldman Sachs Group              Financials   238.05  19.20   476.10
58    Lockheed Martin Corp             Industrials   312.93  12.72   625.86
65              3M Company             Industrials   232.49   8.95   464.98
75         Priceline Group  Consumer Discretionary  1762.23  74.45  3524.46
91  Unitedhealth Group Inc             Health Care   209.75   9.60   419.50

In [34]:
df[df['EPS']>10]

,Name,Sector,Price,EPS,new
4,Allergan Plc,Health Care,171.81,15.42,343.62
7,Amgen,Health Care,168.93,12.58,337.86
12,Biogen Inc,Health Care,311.92,21.59,623.84
14,Blackrock,Financials,474.05,21.55,948.10
37,Fedex Corp,Industrials,217.75,11.91,435.50
40,General Dynamics Corp,Industrials,198.70,10.07,397.40
44,Alphabet Class C,Information Technology,1018.48,29.87,2036.96
45,Alphabet Class A,Information Technology,1034.09,29.87,2068.18
46,Goldman Sachs Group,Financials,238.05,19.20,476.10
50,International Business Machines,Information Technology,151.40,13.66,302.80
58,Lockheed Martin Corp,Industrials,312.93,12.72,625.86
75,Priceline Group,Consumer Discretionary,1762.23,74.45,3524.46