In [10]:
import pandas as pd
df=pd.read_csv(r'/Users/algo trading 2026/batch36/11_pandas/unicorn.csv')
df

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [11]:
df=df.set_index('Company')

In [14]:
# df.reset_index()
df

,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
Company,,,,,,,,
Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...
Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [15]:
df.loc['Klarna','City']

'Stockholm'

In [16]:
df.iloc[4,3]

'Stockholm'

In [17]:
df.iloc[-1,-1]

np.float64(620.0)

In [18]:
df.loc['Zwift','Funding']

np.float64(620.0)

In [20]:
df.loc['Bytedance':'SpaceX','Valuation':'Date Joined']

           Valuation Date Joined
Company
Bytedance        180  07-04-2017
SpaceX           100  01-12-2012

In [22]:
df.loc['Bytedance':'Klarna','Valuation':'Industry']

           Valuation Date Joined                         Industry
Company
Bytedance        180  07-04-2017          Artificial intelligence
SpaceX           100  01-12-2012                            Other
SHEIN            100  03-07-2018  E-commerce & direct-to-consumer
Stripe            95  23-01-2014                          Fintech
Klarna            46  12-12-2011                          Fintech

In [24]:
df.iloc[-3:,-3:]

              Continent  Year Founded  Funding
Company
Zihaiguo           Asia          2018     80.0
Zopa             Europe          2005    792.0
Zwift     North America          2014    620.0

In [26]:
df.iloc[2:4,3:6]

                  City        Country      Continent
Company
SHEIN         Shenzhen          China           Asia
Stripe   San Francisco  United States  North America

In [30]:
df=df.drop('Continent',axis=1)

In [32]:
df=df.drop('Zopa',axis=0)

In [33]:
df

,Valuation,Date Joined,Industry,City,Country,Year Founded,Funding
Company,,,,,,,
Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,2012,NaN
SpaceX,100,01-12-2012,Other,Hawthorne,United States,2002,7.0
SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,2008,2.0
Stripe,95,23-01-2014,Fintech,San Francisco,United States,2010,2.0
Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,2005,4.0
...,...,...,...,...,...,...,...
Yunxuetang,1,29-03-2021,Edtech,Suzhou,China,2011,389.0
Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,2012,379.0
Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,2015,990.0
Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,2018,80.0
Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,2014,620.0